manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badhi
      url-base: https://github.com/badhi
  projects:
    - name: zmk
      remote: badhi
      repo: zmk-pmw3610-driver  # 실제 저장소 이름을 정확히 지정해야 합니다.
      revision: main
      import: app/west.yml
  self:
    path: config
